# Generated by Django 4.0.3 on 2022-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='nombre_place',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
