# Generated by Django 4.0.4 on 2022-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('lieu', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('categorie', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
