# Generated by Django 4.0.3 on 2022-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
